// Generated by @dweb-cloud/safenv - GenTsPlugin
// Config: env-examples
// Validator Style: none
// Export Mode: none
// Generated at: 2025-08-12T06:55:01.584Z
// DO NOT EDIT - This file is auto-generated

/**
 * TypeScript interface for env-examples environment variables
 */
export interface EnvExamplesVariables {
  /** node开发环境 */
  NODE_ENV?: boolean
}